branch-defaults:
  master:
    environment: ghsa-network-analysis-dev
    group_suffix: null
global:
  application_name: ghsa-network-analysis
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 5.4
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
